pipeline:
  build:
    image: debian:sid-slim
    commands:
      - apt-get update -y
      - apt-get install -y gcc g++ mingw-w64
      - mkdir bin/ lib/
      # Build binary for Linux
      - g++ -o bin/ooz *.cpp
      # Build binary for Windows
      - x86_64-w64-mingw32-g++ -o bin/ooz.exe *.cpp
      # Build library for Linux
      - g++ -fpic -c *.cpp
      - g++ -shared -o lib/libooz.so *.o
      # Build library for Windows
      - x86_64-w64-mingw32-g++ -fpic -c *.cpp
      - x86_64-w64-mingw32-g++ -shared -o lib/ooz.dll *.o
    when:
      event: [push, tag]

  release:
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - bin/*
        - lib/*
      draft: true
    when:
      event: tag
